#!/usr/bin/env python3
#
# Copyright (C) 2000 ${AUTHOR_NAME} ${AUTHOR_EMAIL}
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Command to get the fibonacci number by a given index."""

import argparse

from fibonacci import fibonacci


def main():
    """Parse user input and output the result."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'index', type=int, help='Index of the fibonacci sequence.')
    args = parser.parse_args()
    result = fibonacci(args.index)
    print(f'fibonacci({args.index}) = {result}')


if __name__ == '__main__':
    main()
